### ISSUE TITLE
YAML configuration

### ISSUE THREAD

**Issue by CromFr** [nwn2dev/nwnx4#16]
YAML could be a good candidate for replacing current ini configuration.

Benefits are:
- Tree-like configuration
    + More comprehensive structure
    + we could configure nwnx4 and all plugins with one single config file (not very practical for providing plugins documentation)
- Logger could be a configured in a yaml object, that could be anchored/inherited for plugins log configuration
- Can check values types
- Supports multiline text, arrays, maps, ...

Example:
```yamlnwn2server:
  location: C:\Program Files (x86)\Atari\Neverwinter Nights 2
  parameters: -module nwnx4demo
  temp: C:\nwn2-temp
  port: 5121
  # Should NWNX disable the general protection fault error dialog ?
  # Note: The watchdogs may fail to restart the server properly if this dialog stays open
  # 0 = do not disable the GPFault dialog
  # 1 = disable the GPFault dialog
  # default: 1
  disable_error_box: true


restart:
  # How long should NWNX wait for the server to shutdown gracefully 
  # before it ends the server process forcefully ?
  # Value = seconds to wait
  # default: 10 seconds
  gracefulShutdownTimeout: 10

  # You can enter a server message that will be sent to all players
  # as NWNX tries to shutdown the server.
  # Value = message
  # default: none
  gracefulShutdownMessage: Server is shutting down NOW!

  # How long should the shutdown server message be displayed ?
  # Value = seconds to wait before actual shutdown
  # default: 5 seconds
  gracefulShutdownMessageWait: 5

  # If you want NWNX to execute a CMD or BAT file before restarting the server after
  # a crash, specify it's name here. If you leave this setting empty, no program
  # will be run. NWNX will wait for the program to finish before it continues.
  # no default
  restart_cmd: nwnx_restart.cmd


watchdogs:
  # Should NWNX restart the server if it locks up ?
  # This can happen if the server is still running, but does not react to gamespy queries any more.
  gamespy:
    enabled: true
    # How often should the gamespy watchdog query the server ?
    # Note: The server will be restarted if it does not react to a certain number of
    # queries in a row. See setting gamespyTolerance below.
    # default: every 30 seconds
    interval: 30
    # How often may the server not react to gamespy queries ?
    # Note: The server will be restarted if it does not react this many queries in a row
    # Example: gamespyInterval = 30 and gamespyTolerance = 4 means that the server will
    # be restarted if it does not react within 2 minutes 
    # default: 4 queries
    tolerance: 4
    # How long should NWNX wait before the gamespy watchdog kick in ?
    # Note: Give the server enough time to load the module, otherwise the watchdog will start to complain
    # Value = seconds to wait
    # default: 30 seconds
    delay: 30
  # Should NWNX restart the server if the server process has gone away ?
  process: 
    enabled: true

logs:
  mode: append
  max_file_size: 50M
  verbosity: error
```
